name: flutter_once
description: Want to show a widget once periodically (Daily - Weekly - Monthly - Yearly - Any period)? We got your back.
version: 1.0.1
homepage: https://github.com/MostafaSolimanMO/flutter_once

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  once: ^1.1.1

dev_dependencies:
  flutter_lints: ^1.0.0