name: flutter_once
description: Want to show a widget once periodically (Daily - Weekly - Monthly - Yearly - Any period)? We got your back.
version: 1.1.0
homepage: https://github.com/MostafaSolimanMO/flutter_once

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  once: ^1.2.0

dev_dependencies:
  flutter_lints: ^1.0.0